modified Makefile.tmpl for accepting gz. splitted get_mismatches into get_neighbors

diff --git a/Makefile.tmpl b/Makefile.tmpl
--- a/Makefile.tmpl
+++ b/Makefile.tmpl
@@ -1,4 +1,5 @@
 ### TODO: accept gzip input
+SHELL:=/bin/bash
 
 ### This is placed at data/$(ACC)/ by master Makefile at top-level.
 ### Makefile records only the types (type-theoretic) of procedures (at least for blackbox processes).
@@ -20,10 +21,14 @@ reads/$(ACC)_2.fastq:
 ## Join paired-end reads
 join: reads/$(ACC).join.fq.gz reads/$(ACC).un1.fq.gz reads/$(ACC).un2.fq.gz
 
+reads/$(ACC).un1.fq.gz: reads/$(ACC).join.fq.gz
+	if [[ ! -e reads/$(ACC).un1.fq.gz ]]; then echo "$(ACC).un1.fq.gz not found"; exit 1; fi
+reads/$(ACC).un2.fq.gz: reads/$(ACC).join.fq.gz
+	if [[ ! -e reads/$(ACC).un2.fq.gz ]]; then echo "$(ACC).un2.fq.gz not found"; exit 1; fi
 reads/$(ACC).join.fq.gz:
-TODO
-reads/$(ACC).un1.fq.gz:
-reads/$(ACC).un2.fq.gz:
+	cd reads; fastq-join -v ' ' <(zcat $(ACC)_1.fastq.gz) <(zcat $(ACC)_2.fastq.gz) -r $(ACC).join.log -o $(ACC).%.fq \
+	&& gzip $(ACC).join.fq && gzip $(ACC).un1.fq && gzip $(ACC).un2.fq
+	# > >
 
 reads/$(ACC).un1.fq: reads/$(ACC).join.fq
 	if [[ ! -e reads/$(ACC).un1.fq ]]; then echo "$(ACC).un1.fq not found"; exit 1; fi
@@ -32,15 +37,16 @@ reads/$(ACC).un2.fq: reads/$(ACC).join.fq
 reads/$(ACC).join.fq: reads/$(ACC)_1.fastq reads/$(ACC)_2.fastq
 	cd reads; fastq-join -v ' ' $(ACC)_1.fastq $(ACC)_2.fastq -r $(ACC).join.log -o $(ACC).%.fq
 
-## Alignment using whole set of monomers & reads
+## Alignment using whole set of monomers & reads; index must be present beforehand;
+## TODO: raw sam is too big to retain - streamline into aligned.sam or bam?
 align: alignments/$(ACC).join.single.sam alignments/$(ACC).un1.single.sam alignments/$(ACC).un2.single.sam
 
-alignments/$(ACC).join.single.sam: reads/$(ACC).join.fq
-	bwa mem ../monomers/single_mon.fa reads/$(ACC).join.fq > alignments/$(ACC).join.single.sam 2> $(ACC).join.single.log
-alignments/$(ACC).un1.single.sam: reads/$(ACC).un1.fq
-	bwa mem ../monomers/single_mon.fa reads/$(ACC).un1.fq > alignments/$(ACC).un1.single.sam 2> $(ACC).un1.single.log
-alignments/$(ACC).un2.single.sam: reads/$(ACC).un2.fq
-	bwa mem ../monomers/single_mon.fa reads/$(ACC).un2.fq > alignments/$(ACC).un2.single.sam 2> $(ACC).un2.single.log
+alignments/$(ACC).join.single.sam: reads/$(ACC).join.fq.gz
+	bwa mem ../monomers/single_mon.fa <(zcat reads/$(ACC).join.fq.gz) > alignments/$(ACC).join.single.sam 2> $(ACC).join.single.log
+alignments/$(ACC).un1.single.sam: reads/$(ACC).un1.fq.gz
+	bwa mem ../monomers/single_mon.fa <(zcat reads/$(ACC).un1.fq.gz) > alignments/$(ACC).un1.single.sam 2> $(ACC).un1.single.log
+alignments/$(ACC).un2.single.sam: reads/$(ACC).un2.fq.gz
+	bwa mem ../monomers/single_mon.fa <(zcat reads/$(ACC).un2.fq.gz) > alignments/$(ACC).un2.single.sam 2> $(ACC).un2.single.log
 
 ## Get Sorted SAM/BAM for Aligned Reads
 aligned_sam: alignments/$(ACC).join.aligned.sort.sam alignments/$(ACC).un.aligned.sort.sam
